name: Setup Linux system dependencies
description: Install system libraries required for Tauri/Rust builds on Ubuntu

runs:
  using: composite
  steps:
    - name: Install Linux system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pkg-config \
          libglib2.0-dev \
          libgtk-3-dev \
          libsoup-3.0-dev
